site_name: dockler
site_description: Simple multi-host container-based job scheduler
repo_url: https://github.com/devkoriel/dockler
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/devkoriel">devkoriel</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
